import { Link, useParams } from 'react-router-dom';
import { interns } from '../data/interns';
import { Button } from '../components/ui/Button';

export function InternProfilePage() {
  const { slug } = useParams();
  const intern = interns.find((item) => item.slug === slug);

  if (!intern) {
    return (
      <section className="container-page py-24 text-center">
        <h1 className="font-heading text-4xl font-bold">Intern not found</h1>
        <Link to="/intern" className="mt-6 inline-block">
          <Button>Back to Internships</Button>
        </Link>
      </section>
    );
  }

  return (
    <section className="container-page py-16 md:py-24">
      <div className="mx-auto max-w-3xl text-center">
        <p className="text-sm text-content-tertiary">{intern.role}</p>
        <h1 className="mt-2 font-heading text-4xl font-bold md:text-6xl">{intern.name}</h1>
        <p className="mt-3 text-lg text-content-tertiary">{intern.university}</p>
        <div className="mx-auto mt-10 flex h-[320px] max-w-sm items-end justify-center rounded-s bg-background-muted p-4 md:h-[369px]">
          <p className="text-sm text-content-tertiary">Art generated by program participant</p>
        </div>
        <blockquote className="mt-10 text-lg italic text-content-secondary">
          “{intern.quote}”
        </blockquote>
        <Link to="/intern" className="mt-10 inline-block">
          <Button variant="secondary">View All Interns</Button>
        </Link>
      </div>
    </section>
  );
}
